version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_username
      - MYSQL_PASSWORD=your_password
    ports:
      - 3307:3307
    volumes:
      - /var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_HOST=db
        - PMA_PORT=3307
      ports:
        - 8010:8010
      depends_on:
        - db
      links:
        - db