version: '3'
services:
  db:
    build:
      context: ./database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pricecompare
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - 3306:3306
    volumes:
      - ~/my/own/datadir:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      environment:
        - PMA_HOST=db
        - PMA_PORT=3306
      ports:
        - 8090:80
      depends_on:
        - db
      